### ISSUE TITLE
[feature request] link to docs in site header

### ISSUE THREAD

**Issue by rubdos** [coala/website-old#14]
> <rubdos> Perhaps a link in the header too?
> <rubdos> that's mainly where I searched
> <sils1297> ah that's a good idea
> <sils1297> maybe somehow aligned
> <sils1297> so it is recognizable as something else moving you outside the website
> <rubdos> yes, good idea
> <gitter> [Github] cw1 synchronize a Pull Request to coala-analyzer/coala-artwork: Add coala website to the fosdem flyer https://github.com/coala-analyzer/coala-artwork/pull/18
> <sils1297> @rubdos would you mind filing a bug for that at coala-analyzer/website ? A lot of stuff going on right now that would really help...

Please add some link in the site header, as that was where I searched for a documentation link.

Yes, I'm blind, I know, it was in a font that almost blew my eyes out on the page itself, but having a link on the header would be nice.

Thank you :)

**Comment by Adrianzatreanu** [comment]
Do we want this? Where exactly would you like the link to be?

**Comment by Makman2** [comment]
Though #17 is planned on long-term, this would be nice. (so @rubdos can at least find our beloved docs :D)
@rubdos Maybe we shall just rename `More info` to `Documentation`? Since the header entries are directly linked to the page contents there's not much play for easily inserting a link^^

**Comment by rubdos** [comment]
Yes, that would help a lot, @Makman2 :) I probably `ctrl-f`'d for `doc` or something.

**Comment by sils** [comment]
I added a link list on top so people can go from there to what they'd like to know, let me know if you like it!
