### ISSUE TITLE
Webpage doesn't load content from _posts and gives a blank page

### ISSUE THREAD

**Issue by sudheesh001** [coala/website-old#16]
## Steps to reproduce
1. Clone the repository
2. Run `jekyll serve`

Result:
<img width="1440" alt="screen shot 2016-02-04 at 7 44 37 am" src="https://cloud.githubusercontent.com/assets/4545925/12803779/3e0be7fe-cb13-11e5-8671-6a10ac2d6461.png">

Expected:
<img width="1440" alt="screen shot 2016-02-04 at 7 45 56 am" src="https://cloud.githubusercontent.com/assets/4545925/12803796/52cc4b52-cb13-11e5-860f-55a5776864a1.png">

Stacktrace:

```
[7:44:27] sudheeshsinganamalla:coala-website git:(gh-pages) $ jekyll serve
Configuration file: /Users/sudheeshsinganamalla/Documents/coala-website/_config.yml
            Source: /Users/sudheeshsinganamalla/Documents/coala-website
       Destination: /Users/sudheeshsinganamalla/Documents/coala-website/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.063 seconds.
 Auto-regeneration: enabled for '/Users/sudheeshsinganamalla/Documents/coala-website'
Configuration file: /Users/sudheeshsinganamalla/Documents/coala-website/_config.yml
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
[2016-02-04 07:44:35] ERROR `/favicon.ico' not found.
[2016-02-04 07:44:35] ERROR `/favicon.ico' not found.
```

**Comment by sils** [comment]
uhm @sudheesh001 can you try reproducing with master? There was a switch to jekyll 3.

**Comment by sils** [comment]
for me it looks fine, can't reproduce it, get the same error though
