### ISSUE TITLE
New "serious" landing page

### ISSUE THREAD

**Issue by Makman2** [coala/website-old#17]
We need something that provides more content and more information about coala since we have grown. I have found the [blender.org](https://www.blender.org/) wordpress template, I like it since it's simple but stylistic.

The wordpress template is hosted here:
https://git.blender.org/gitweb/gitweb.cgi/blender-org.git

As stated in our super-duper-private-meeting (with me, @sils1297 and @fneu) something like a collection of links is needed, like here: https://www.blender.org/support/

**Comment by hemangsk** [comment]
Hello fellow coalaians ! 
I'm really looking forward to work on the coala website.

Is the issue still relevant? I found this mockup shared on a issue thread (can't recall exactly as it was two three days back) [mockup](https://app.moqups.com/coala/YLGaMKWoDy/view/page/a302a5701)

Studied this mockup design today, the features are simply awesome. especially the bear search option, also I have experience with some more minimalistic design approaches.
Actually I would love to implement this mockup as a week long project! 💻 😮  👍

**Comment by sils** [comment]
Hi, most certainly! Let us know what you need. @tushar-rishav and @mr-karan had prototypes for the live editor and the bear search thingy respectively.

**Comment by sils** [comment]
The mockup you fonud is actually the most recent one and the one we're most likely to want ;)

**Comment by hemangsk** [comment]
That sounds great! I will collaborate with @tushar-rishav and @mr-karan 
😄 👍 👍 👍

**Comment by hemangsk** [comment]
Just a crude plan, 
- To create a `new-site` branch, on my fork of coala/website repo.
- Start with design process, creating the markup following our mockup.
- Have placeholders for components which are being worked upon.
Thoughts? would be of great help to me to get up & running 😃

**Comment by sils** [comment]
@hemangsk maybe even make a new repo? It's not like it has anything related to this one does it?

**Comment by hemangsk** [comment]
@sils that will be much better. :+1:  new repo sounds good,  looks like we are all set to start :rocket: can you create the repo,  I don't have the apt privileges to create repo in coala currently
OR also another option I can create a repo in my github account, and work in it with MIT license, which one sounds better?

**Comment by jayvdb** [comment]
https://coala.io/ happened
