### ISSUE TITLE
Show Contributors

### ISSUE THREAD

**Issue by sils** [coala/website-old#18]
I like the contributors section on https://pivotfinland.com/pytest-sugar/ - want that!

**Comment by arafsheikh** [comment]
This will help: https://developer.github.com/v3/repos/#list-contributors

**Comment by sils** [comment]
Yes we'll make an IGitt endpoint for it at https://gitlab.com/gitmate/IGitt

**Comment by AbdealiLoKo** [comment]
You don't need an end point. List of Contributors is public, so you wouldn't need a github token or something.
It can be directly fetched from github using JS ajax calls ?

**Comment by SanketDG** [comment]
We did definitely want the top 5/10 contributors, not the whole list.
