### ISSUE TITLE
capabilities are unclear

### ISSUE THREAD

**Issue by sils** [coala/website-old#30]
> However, I must say that very critical info for first-time users is still unavailable or very vaguely documented. For example, I still have no clue what sort of analysis can be obtained from this page : https://github.com/coala-analyzer/coala-bears/wiki/Available.... I can see a bunch of Bears but that's your terminology. I would rather prefer a brief summary of the tool's analysis or atleast a link to the static analyzer which a specific bear wraps over. For e.g. "AlexBear" - I honestly have no clue what that or 90% of the other bears end up doing with my source code.
> 
> You have put so much effort in the implementation, please improve clarity/coverage of documentation.

from https://news.ycombinator.com/reply?id=11535990&goto=item%3Fid%3D11531718

**Comment by sils** [comment]
see also https://docs.google.com/spreadsheets/d/1ZJTe1nFsWuKxVdRgHOlpKNI1cLHb4QgY7aAq9tOaa9w/edit?usp=sharing for capabilities

**Comment by sils** [comment]
Filed https://github.com/coala-analyzer/coala-bears/issues/332 about the bear-quality-offensive we have planned but not yet written down for this release.

**Comment by Adrianzatreanu** [comment]
Hey where exactly would you want this info about the bears? a gist or something?

**Comment by sils** [comment]
I have no idea, ideally coala-bears#332 would be done and then we'd generate a website from that or so :P

Actually yesterday night I thought about this, we can do it right now:

write a little python script that collects all bears and outputs all it's info as markdown, we use that to generate a neat website somewhere and link to that from our website

**Comment by Adrianzatreanu** [comment]
i'll do this tonight, i was just gathering info now :) if you want this to be done right away, please assign someone else

**Comment by sils** [comment]
no this is more of a long term thing actually _but_ very important

**Comment by sils** [comment]
this got way better by now with the https://github.com/coala-analyzer/bear-docs

**Comment by jayvdb** [comment]
Closing issue in old repo.

I think https://coala.io/#/languages has mostly covered this, but it is still 'bear'-focused, so https://github.com/coala/landing-frontend/issues/250 covers that problem.
