### ISSUE TITLE
coala logo isn't shown anywhere at website

### ISSUE THREAD

**Issue by tushar-rishav** [coala/website-old#39]
Logo is important. Let's decide where we want the logo to be shown.

**Comment by daminisatya** [comment]
@tushar-rishav @sils1297 It even requires a favicon.

**Comment by sils** [comment]
Indeed, anyone wants to help out? Shouldn't be too hard I guess

**Comment by daminisatya** [comment]
@sils1297 I would like to work on this :)

**Comment by sils** [comment]
Hi,

please don't ping me personally for such things. Everyone can do them - and almost everyone pings me. If you don't address a person specifically you'll likely get help faster from other people!

(Don't worry, this is not a problem but keeping things general is usually a good policy :))

**Comment by sils** [comment]
there you go :)

**Comment by daminisatya** [comment]
Yes will do so. :) Thank you

**Comment by sils** [comment]
done at https://new.coala.io
