### ISSUE TITLE
We should have a generic bear as the first example instead of PEP8Bear

### ISSUE THREAD

**Issue by underyx** [coala/website-old#43]
Possibly SpaceConsistencyBear, also, we need to change the `**/*.py` part too.

**Comment by jayvdb** [comment]
Closing as issues in this repo needs to be killed before they attract GCI nonsense, but ...

We still do have Python as the first example on the new website https://coala.io/#/home hosted in https://github.com/coala/landing-frontend/ .  I tend to agree that choosing a different default will show off coala better.

Created https://github.com/coala/landing-frontend/issues/249
