### ISSUE TITLE
Setup Details could be called something a  normal person would call it such as 'Get It'

### ISSUE THREAD

**Issue by underyx** [coala/website-old#45]

**Comment by jschwarzwalder** [comment]
On [Coala Analyzer](http://coala-analyzer.org/)
As a new user I see : 
coala
Issue Tracker — Code — Docs — FAQ — Blog — Donate

There is no link to get started or download, so I didn't know what action to take

**Comment by jayvdb** [comment]
I think the website has fixed this.
