### ISSUE TITLE
people scroll the website searching for the code

### ISSUE THREAD

**Issue by sils** [coala/website-old#48]
the user says he'd expect it in the setup section. Get it, use it, commit it, develop it

**Comment by daminisatya** [comment]
@sils1297 Can you elaborate on this please

**Comment by sils** [comment]
This was during usability testing, the subject was unable to find our github page on our website.

**Comment by sudoankit** [comment]
The website is powered by Jekyll. It wouldn't be difficult to add a github ribbon like these? http://tholman.com/github-corners/

**Comment by jayvdb** [comment]
Looks like this might have already been fixed on the old website, ...

We have a source link on the new website.
