### ISSUE TITLE
Meta information on Slack, tells users that coala is written with lower case c 

### ISSUE THREAD

**Issue by jschwarzwalder** [coala/website-old#49]
I tried to share with my classmates and a women in coding group about coala on our Slack Channels. The meta for the site displayed telling both groups that  **coala is written with a lower case c**

> `coala is a simple COde AnaLysis Application. Its goal is to make static code analysis easy while remaining completely modular and therefore extendable and language independent. coala is written with a lower case c.`

http://prntscr.com/bchcfs

When promoting the project to new users do we need to tell them that coala is written with a lower case c?

**Comment by Makman2** [comment]
I think that makes coala kind of "rememberable" :)

**Comment by sils** [comment]
changed it, file a new issue if you stil ldislike it :)
