### ISSUE TITLE
Show graphs of coala performance

### ISSUE THREAD

**Issue by adtac** [coala/website-old#50]
between versions (and if it won't be too computationally costly, every `n` commits to get a smoother graph)

**Comment by sils** [comment]
so somebody could write a script to measure the performance by running it 5ish times and then we run it for a number of commits? It must be the same machine of course and we may even need an HDD and SSD measurement...

**Comment by jayvdb** [comment]
Created https://github.com/coala/meta/issues/102

**Comment by adtac** [comment]
I also wrote a script to automatically do this and posted it as a comment (bad idea, I know). No idea where it went ^^
