### ISSUE TITLE
User Story: I am a contribute and might want to know when a test was last updated to know whether a new patch/version will be utilized

### ISSUE THREAD

**Issue by jschwarzwalder** [coala/website-old#51]
Will this information be available? Where should they look?

This would be an advanced user, so this isn't needed that often

**Comment by jayvdb** [comment]
Hi Jami, I dont understand this completely.

It looks like you're asking about coala *bear* version history, and I think this is something we do not yet have on the website.

Could you try explaining it again, over at the new website repo : https://github.com/coala/frontend-landing
