### ISSUE TITLE
User Story: I heard about coala and I want to know if it supports a language that I have written code

### ISSUE THREAD

**Issue by jschwarzwalder** [coala/website-old#53]

**Comment by ankit01ojha** [comment]
@jschwarzwalder : Search the language of your code here at : https://github.com/coala/bear-docs/blob/master/README.rst . If its there then its fine :)

**Comment by jayvdb** [comment]
We have a click-baity `Languages` link on the new front page repo at https://github.com/coala/frontend-landing
