### ISSUE TITLE
Contributors list on the website should show the list in descending order of number of commits

### ISSUE THREAD

**Issue by sils** [coala/website-old#54]
_From @shaswatrungta on August 12, 2016 7:32_

_Copied from original issue: coala-analyzer/coala#2601_

**Comment by sils** [comment]
_From @gitmate-bot on August 12, 2016 7:33_

Thanks for reporting this issue! A coalaian will look at it soon.

**Comment by sils** [comment]
hey @shaswatrungta thanks for reporting this. This is an issue with the website, I'll move the issue over there.

Indeed the people list is a bit buggy but often it actually shows it right for me :P CC @arafsheikh I think he implemented this. Often is certainly not enough ;)

**Comment by tushar-rishav** [comment]
@sils1297 @arafsheikh Has been solved in new website.

**Comment by daminisatya** [comment]
![selection_336](https://cloud.githubusercontent.com/assets/6227784/19025601/aea6b848-8938-11e6-9e35-aae7be59af6b.png)

Yes this issue can be closed. It is resolved. @sils1297
