### ISSUE TITLE
We don't fully support Mac

### ISSUE THREAD

**Issue by adtac** [coala/website-old#57]
but the website says so

**Comment by sils** [comment]
what's the problem with mac support?

**Comment by adtac** [comment]
we don't do tests (removed Travis), so we don't what works, what doesn't, right?

**Comment by sils** [comment]
mac is unix like we dropped it because it almost never found bugs for us; coala works well on mac AFAIK and we do have a lot of mac users

**Comment by adtac** [comment]
Closing then
