### ISSUE TITLE
Adding a README.md

### ISSUE THREAD

**Issue by KrishMunot** [coala/website-old#62]
Since the repo lacks a README file for newcomers to learn about the website, It would be highly appreciated if someone would contribute a well written README.

**Comment by Yomojet** [comment]
Get me assigned.

**Comment by sils** [comment]
:+1:

**Comment by vedantrathore** [comment]
@sils @KrishMunot can I work on this issue?

**Comment by sils** [comment]
@Yomojet any progress? Still on this?

**Comment by KrishMunot** [comment]
@vedantrathore Please send a pull request and we can collaborate that way.

**Comment by KrishMunot** [comment]
@sils We haven't seen any progress from @Yomojet yet. Is he interested in contributing?

**Comment by jayvdb** [comment]
The readme only needs to say that this repository is deprecated, archived, no longer wanting PRs.

**Comment by KrishMunot** [comment]
Made a PR https://github.com/coala/website-old/pull/76 to solve this

**Comment by manankalra** [comment]
@jayvdb I would like to work on this.

**Comment by manankalra** [comment]
@jayvdb Submitted a PR. Can you review this?
