### ISSUE TITLE
New short URL for all bugs

### ISSUE THREAD

**Issue by jayvdb** [coala/website-old#65]
https://coala.io links to http://bugs.coala-analyzer.org/ , which should be a coala.io URL, but http://bugs.coala.io/ doesnt exist, and https://coala.io/bugs and https://coala.io/issues are also 404 .

**Comment by ashwini0529** [comment]
@jayvdb What exactly do you want these links to be redirected to?

**Comment by ankit01ojha** [comment]
@jayvdb Where you found these short URLs : http://bugs.coala.io/ ,  https://coala.io/bugs , https://coala.io/issues

**Comment by jayvdb** [comment]
Stale and further activity in this deprecated repo is not desirable.
