### ISSUE TITLE
Implementation of mockup 

### ISSUE THREAD

**Issue by hemangsk** [coala/website-old#66]
Continued from #17 
Here's the [app.moqups](https://app.moqups.com/coala/YLGaMKWoDy/view/page/ad64222d5) mockup for quick reference.

just wanted to take your feedback  to know if it is going in right direction or not. 

These are some basic functionality changes yet to be done,
- getting started section should have multiple languages support
- get involved tab should have real data
- gitter chat embed
- and a lot of more todos

some screenshots from the local environment,
![screencapture-localhost-8080-coala-blog-201-1481232278351](https://cloud.githubusercontent.com/assets/13018570/21030085/b6419032-bdc2-11e6-829f-d1f46e9a5d14.png)
![screencapture-localhost-8080-coala-blog-201-1481235676160](https://cloud.githubusercontent.com/assets/13018570/21030116/e3e559c4-bdc2-11e6-9be0-33d30fc3e6cd.png)

Implementation [here](https://hemangsk.github.io/coala-web-dev/)

**Comment by Makman2** [comment]
not bad , like it :)
though with this design we should pay attention to contrast, meaning how to separate different paragraphs and sections well so you can grasp the structure better as a reader.

**Comment by hemangsk** [comment]
I agree entirely..reader should feel highly motivated to use coala and how to use it, by the time they scroll down completely

**Comment by hemangsk** [comment]
The current procedure to separate different sections is using a title, having top margin, and a specific font style, like 'installing' and 'getting started' on the  [main page](https://hemangsk.github.io/coala-web-dev)

**Comment by Makman2** [comment]
could you maybe highlight those titles somehow? Maybe underline them?

**Comment by sils** [comment]
done at https://new.coala.io
